---
title: "Homework 5"
author: "Kiara Hodo"
date: "11/17/2021"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Reading Data into R

```{r}
library(readr)
homicide_data <- read_csv("~/Fall 21 CSU/R Programming/Final Project/data/homicide-data.csv")
homicide_data
```

# Filtering down to Atlanta

```{r}
library(dplyr)
atl_homicides <- homicide_data %>%
  filter(city == "Atlanta")
atl_homicides
```
# Seperating Data into Solved and Unsolved 
```{r}
library(forcats)
library(sf)

unsolved <- atl_homicides %>%
  mutate(unsolved = disposition %in% c("Closed without arrest", "Open/No arrest"))
  


```

# Making lower layer map of GA (Tigris package)
```{r}
library(tigris)
ga_counties <- counties(state = "GA", cb = TRUE, class = "sf")

fulton_atl <- ga_counties %>%
  filter(COUNTYFP == 121)
fulton_atl

?tracts
fulton_tracts <- tracts(state = "GA", county = 121, cb = TRUE)

library(ggplot2)

ggplot() + 
  geom_sf(data = fulton_atl) +
  geom_sf(data = fulton_tracts)

```
```{r}
fulton_homicdes <- st_as_sf(unsolved, coords = c("lon", "lat")) %>% 
  st_set_crs(4269)

```

# Making dots on map 
```{r}

?fct_lump
?factor

fulton_homicdes %>%
  count(victim_race)

race_homicides <- fulton_homicdes %>%
  dplyr::mutate(victim_race = forcats::fct_lump(victim_race, n = 3)) %>%
  dplyr::count(victim_race)


library(viridis)

fulton_race_map <- ggplot() + 
  geom_sf(data = fulton_tracts, color = "lightgray") + 
  geom_sf(data = race_homicides, aes(color = victim_race)) +
  scale_color_viridis(name = "Victim's Race", discrete = TRUE) 

fulton_race_map

fulton_case_map <- ggplot() + 
  geom_sf(data = fulton_tracts, color = "lightgray") + 
  geom_sf(data = fulton_homicdes, aes(shape = disposition)) +
  scale_color_viridis(name = "Case Disposition", discrete = TRUE) 

fulton_case_map
```
# Faceting Maps 

```{r}

fulton_race_map + facet_grid(victim_race ~ .) 

fulton_case_map + facet_grid(disposition ~ .)

fulton_case_map + facet_grid(disposition ~ victim_race)
```


